name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  JAVA_VERSION: '17'
  QUARKUS_VERSION: '3.9.0'
  GRAALVM_VERSION: '22.3.0'

jobs:
  # Code quality and security checks
  code-quality:
    name: Code Quality & Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Run SpotBugs
      run: |
        cd vuln-patcher
        mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.1.0:spotbugs
    
    - name: Run PMD
      run: |
        cd vuln-patcher
        mvn pmd:pmd pmd:cpd
    
    - name: Run Checkstyle
      run: |
        cd vuln-patcher
        mvn checkstyle:checkstyle
    
    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd vuln-patcher
        mvn verify sonar:sonar \
          -Dsonar.projectKey=intelliswarm_vuln-patcher \
          -Dsonar.organization=intelliswarm \
          -Dsonar.host.url=https://sonarcloud.io
    
    - name: Upload analysis reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: analysis-reports
        path: |
          vuln-patcher/target/spotbugs/
          vuln-patcher/target/pmd/
          vuln-patcher/target/checkstyle-result.xml

  # Security vulnerability scanning
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'vuln-patcher'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'
    
    - name: Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'vuln-patcher'
        path: './vuln-patcher'
        format: 'HTML'
        args: >
          --enableRetired
          --enableExperimental
    
    - name: Upload OWASP dependency check results
      uses: actions/upload-artifact@v4
      with:
        name: owasp-dependency-check-report
        path: reports/

  # Build and test
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [code-quality]
    
    strategy:
      matrix:
        java: [17, 21]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    
    - name: Set up Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        ollama serve &
        sleep 10
        # Pull required models
        ollama pull deepseek-coder:33b
        ollama pull mixtral:8x7b
        ollama pull codellama:34b
    
    - name: Build with Maven
      run: |
        cd vuln-patcher
        mvn clean compile
    
    - name: Run unit tests
      run: |
        cd vuln-patcher
        mvn test
    
    - name: Run integration tests
      run: |
        cd vuln-patcher
        mvn verify -Pit
    
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests - Java ${{ matrix.java }}
        path: vuln-patcher/target/surefire-reports/*.xml
        reporter: java-junit
    
    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./vuln-patcher/target/site/jacoco/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  # Native build test
  native-build:
    name: Native Build with GraalVM
    runs-on: ubuntu-latest
    needs: [build-test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
        version: ${{ env.GRAALVM_VERSION }}
        components: 'native-image'
        cache: maven
    
    - name: Build native executable
      run: |
        cd vuln-patcher
        mvn package -Pnative -DskipTests
    
    - name: Test native executable
      run: |
        cd vuln-patcher
        ./target/vuln-patcher-1.0.0-SNAPSHOT-runner --version

  # Container build and scan
  container-build:
    name: Container Build and Security Scan
    runs-on: ubuntu-latest
    needs: [build-test, security-scan]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build JAR
      run: |
        cd vuln-patcher
        mvn package -DskipTests
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build container image
      uses: docker/build-push-action@v5
      with:
        context: ./vuln-patcher
        file: ./vuln-patcher/src/main/docker/Dockerfile.jvm
        push: false
        tags: vuln-patcher:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run Trivy container scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: vuln-patcher:${{ github.sha }}
        format: 'sarif'
        output: 'container-scan-results.sarif'
    
    - name: Upload container scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'container-scan-results.sarif'

  # Performance tests
  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: [build-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven
    
    - name: Run JMH benchmarks
      run: |
        cd vuln-patcher
        mvn clean compile
        mvn exec:java -Dexec.mainClass="ai.intelliswarm.vulnpatcher.benchmarks.BenchmarkRunner"
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: jmh-benchmark-results
        path: vuln-patcher/target/jmh-results.json

  # Release
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-test, security-scan, native-build, container-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build release artifacts
      run: |
        cd vuln-patcher
        mvn clean package -DskipTests
        mvn package -Pnative -DskipTests
    
    - name: Create release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false